apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-k8s-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: enscontainerregistry.azurecr.io/demo:$BUILD_NUMBER
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: demo