apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: azure-container-service-aa
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: azure-container-service-aa
    spec:
      containers:
      - name: demo
        image: demo:r1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: dev
          value: "azure-container-service-aa"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-container-service-aa
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: azure-container-service-aa